package:
  name: mdy
  version: "0.0.3"

source:
   path: ..

build:
  entry_points:
    - mdy     = mdy.cli:main_cli

requirements:
  build:
    - python >=3.4

  run:
    - python >=3.4
    - htmd
    - openmm

test:
  commands:
    - mdy  --help

about:
  home: http://www.htmd.org
  license: "Acellera Academic License v1.1"
  license_file: python/mdy/ACADEMIC_LICENCE.txt
